# Generated by Django 4.1.1 on 2022-09-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_product_id',
            field=models.CharField(default=1, max_length=100, verbose_name='ID товара в базе stripe'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100, verbose_name='ID цены товара в базе stripe')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='items.item')),
            ],
        ),
    ]
